version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "daily"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions aiohttp 3.9
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    target-branch: "3.9"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain dependencies for Python aiohttp 3.10
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - dependencies
    target-branch: "3.10"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
