version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
      - autosquash
    schedule:
      interval: "daily"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - dependencies
      - autosquash
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions aiohttp 3.7
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
      - autosquash
    target-branch: "3.7"
    schedule:
      interval: "daily"

  # Maintain dependencies for Python aiohttp 3.7
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - dependencies
      - autosquash
    target-branch: "3.7"
    schedule:
      interval: "daily"
