environment:
  PYPI_PASSWD:
    secure: syNUF3e8AEPY327rWBkKag==
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "tools/build.cmd %PYTHON%\\python.exe -m pip install wheel"
  - "tools/build.cmd %PYTHON%\\python.exe -m pip install -r requirements/ci.txt"

build: false

test_script:
  - "tools/build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  - "tools/build.cmd %PYTHON%\\python.exe setup.py sdist bdist_wheel"

artifacts:
  - path: dist\*

deploy_script:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
          Invoke-Expression "$env:PYTHON\\python.exe -m twine upload dist/* --username fafhrd --password $env:PYPI_PASSWD"
      }

#notifications:
#  - provider: Webhook
#    url: https://ci.appveyor.com/api/github/webhook?id=08c7793w1tp839fl
#    on_build_success: false
#    on_build_failure: True
