environment:
  PYPI_PASSWD:
    secure: HrwOVde4wZoYHJf9bZ5AsQ==
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
  MAKE: C:\MinGW\bin\mingw32-make.exe

install:
  # Ensure the Git Submoduldes have been pulled down too
  - git submodule update --init --recursive

  - >-
    tools/build.cmd %PYTHON%\python.exe -m
    pip install -U pip wheel setuptools
  - '%MAKE% cythonize'
  - "tools/build.cmd %PYTHON%\\python.exe -m pip install -r requirements/ci.txt"

build_script:
  - "tools/build.cmd %PYTHON%\\python.exe -m setup sdist bdist_wheel"

test_script:
  - "tools/build.cmd %PYTHON%\\python.exe -m pytest -c pytest.ci.ini --cov-report xml"

after_test:
  - "tools/build.cmd %PYTHON%\\python.exe -m codecov -f coverage.xml -X gcov"

artifacts:
  - path: dist\*

deploy_script:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
          Invoke-Expression "$env:PYTHON\\python.exe -m twine upload dist/* --username aio-libs-bot --password $env:PYPI_PASSWD --skip-existing"
      }

#notifications:
#  - provider: Webhook
#    url: https://ci.appveyor.com/api/github/webhook?id=08c7793w1tp839fl
#    on_build_success: false
#    on_build_failure: True
