environment:
  PYPI_USER: __token__
  PYPI_PASSWD:
    secure: >-
      E3o5zJvWwZ08zASfNAFzB8nRC8DMNhl2V5B+cH6fpvqt2qBsOeoDhbmSVlxNSdYLhbohI3MGLPAEQ3U8TheQ5UypPx6VRTQDyOkeRC1goENfwHTz3fdWn8eBo3TCSTss5pKK92jWDLNkYirXIyZoz/ukAS2mfxYHMA0GoTiVc46xJzRvuiHjJgUgtsJOX3/rjrw2eFJXyZGyug4Zbvj64PIzzDNPm7umEDnpJzIvG8/CZuIEemZpNiA4FOehIcvMEXR9giox40/EN8Gwn4Jl3Q==
  PYTHONIOENCODING: "utf8:backslashreplace"
  PYTHONLEGACYWINDOWSSTDIO: "1"
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
  MAKE: C:\MinGW\bin\mingw32-make.exe

cache:
  - '%LOCALAPPDATA%\pip\Cache'

init:
  - "chcp 65001"
  - ps: >-
      if($env:APPVEYOR_RDP_DEBUG -eq 'True') {
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }

install:
  # Ensure the Git Submoduldes have been pulled down too
  - git submodule update --init --recursive

  - >-
    tools/build.cmd %PYTHON%\python.exe -m
    pip install -U pip wheel setuptools
  - '%MAKE% cythonize'
  - "tools/build.cmd %PYTHON%\\python.exe -m pip install -r requirements/ci.txt"

build_script:
  - "tools/build.cmd %PYTHON%\\python.exe -m setup sdist bdist_wheel"

test_script:
  - "tools/build.cmd %PYTHON%\\python.exe -m pytest -c pytest.ci.ini --cov-report xml"

after_test:
  - "tools/build.cmd %PYTHON%\\python.exe -m codecov -f coverage.xml -X gcov"

on_finish:
- ps: >-
    if($env:APPVEYOR_RDP_DEBUG -eq 'True') {
      $blockRdp = $true
      iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\.test-results\pytest\results.xml))

artifacts:
  - path: dist\*

deploy_script:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
          Invoke-Expression "$env:PYTHON\\python.exe -m twine upload dist/* --username $env:PYPI_USER --password $env:PYPI_PASSWD --skip-existing"
      }

#notifications:
#  - provider: Webhook
#    url: https://ci.appveyor.com/api/github/webhook?id=08c7793w1tp839fl
#    on_build_success: false
#    on_build_failure: True
