name: Autosquash
on:
  check_run:
    types:
      # Check runs completing successfully can unblock the
      # corresponding pull requests and make them mergeable.
      - completed
  pull_request:
    types:
      # A closed pull request makes the checks on the other
      # pull request on the same base outdated.
      - closed
      # Adding the autosquash label to a pull request can
      # trigger an update or a merge.
      - labeled
  pull_request_review:
    types:
      # Review approvals can unblock the pull request and
      # make it mergeable.
      - submitted
  # Success statuses can unblock the corresponding
  # pull requests and make them mergeable.
  status: {}

jobs:
  autosquash:
    name: Autosquash
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'aio-libs/aiohttp' }}  # not awailable for forks, skip the workflow
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo ${{ github.event.pull_request.head.repo.full_name }}
      - id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: tibdex/autosquash@v2
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
