name: Labels
on:
  pull_request:
    branches:
      - 'master'
    types: [labeled, opened, synchronize, reopened, unlabeled]

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport label added
    if: >-
      ${{
        github.event.pull_request.user.type != 'Bot' &&
        contains(join(github.event.pull_request.labels.*.name, ','), 'backport-')
      }}
    steps:
      - uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const hasBackportLabel = context.payload.pull_request.labels.some(
              label => label.name.startsWith("backport"),
            );
            if (!hasBackportLabel) {
              core.notice("No backport label present, skipping.");
            }
