name: Dependabot post-update
on:
  pull_request_target:
    action: [opened, synchronize, reopened]
    branches:
      - 'master'
      - '[0-9].[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  post-update:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Login
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
    - name: Checkout
      run: |
        gh pr checkout ${{ github.event.pull_request.number }}
    - name: Setup Python
      uses: actions/setup-python@v3.1.1
    - name: Cache PyPI
      uses: actions/cache@v3.0.1
      with:
        key: post-update
        path: ~/.cache/pip
        restore-keys: |
            post-update-
    - name: Update pip-tools
      run: |
        python -m pip install -U pip-tools
    - name: Run pip-compile
      run: |
        make compile-deps
    - name: Commit and push if needed
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Recompile requirements/constraints.txt
