name: Code quality

on:
  push:
  pull_request:
  schedule:
  # Run every Friday at 18:02 UTC
  # https://crontab.guru/#2_18_*_*_5
  - cron: 2 18 * * 5

jobs:
  linters:
    runs-on: ${{ matrix.os }}
    strategy:
      # max-parallel: 5
      matrix:
        python-version:
        - 3.7
        os:
        - ubuntu-18.04
        env:
        - AIOHTTP_NO_EXTENSIONS: 1
        jobs:
        - script: make doc-spelling
          install: >-
            pip install -U
            -r requirements/doc.txt
            -r requirements/doc-spelling.txt
        - script: towncrier --yes
          install: >-
            pip install
            -r requirements/ci.txt
            -r requirements/towncrier.txt
        - script: flake8 aiohttp examples tests
          install: pip install -r requirements/flake.txt
        - script: isort -c -rc aiohttp tests examples
          install: pip install isort
        - script: mypy aiohttp
          install: pip install -r requirements/ci.txt
        - script: |
            python setup.py --verbose sdist bdist_wheel
            twine check dist/*
          install: >-
            pip install
            -r requirements/ci.txt
            -r requirements/doc.txt
        - script: LC_ALL=C sort -c CONTRIBUTORS.txt
    steps:
    - uses: actions/checkout@master
    - name: Sync Git submodules
      if: matrix.jobs.install
      run: git submodule update --init
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python-version }}
    - name: Upgrade Python Toolset
      run: |
        python -m pip install --upgrade pip wheel setuptools
      if: matrix.jobs.install
    - name: Install job deps
      run: ${{ matrix.jobs.install }}
      env: ${{ matrix.env }}
      if: matrix.jobs.install
    - name: Run linter
      run: ${{ matrix.jobs.script }}
      env: ${{ matrix.env }}
